create procedure teamBoxPlayoffsInsert
@season_id						int,
@series_id						varchar(30),
@game_id						int,
@game							int,
@team_id						int,
@atHome							int,
@matchup_id						int,
@points							int,
@pointsAgainst					int   ,
@q1Points						int,
@q1PointsAgainst				int,
@q2Points						int,
@q2PointsAgainst				int,
@q3Points						int,
@q3PointsAgainst				int,
@q4Points						int,
@q4PointsAgainst				int,
@otPoints						int,
@otPointsAgainst				int,
@assists						int   ,
@blocks							int   ,
@blocksReceived					int   ,
@fieldGoalsAttempted			int   ,
@fieldGoalsMade					int   ,
@fieldGoalsPercentage			float,
@foulsOffensive					int   ,
@foulsDrawn						int   ,
@foulsPersonal					int   ,
@foulsTechnical					int   ,
@freeThrowsAttempted			int   ,
@freeThrowsMade					int   ,
@freeThrowsPercentage			float,
@minus							float,
@minutes						varchar(30),
@minutesCalculated				varchar(30),
@plus							float,
@plusMinusPoints				float,
@pointsFastBreak				int   ,
@pointsInThePaint				int   ,
@pointsSecondChance				int   ,
@reboundsDefensive				int   ,
@reboundsOffensive				int   ,
@reboundsTotal					int   ,
@steals							int   ,
@threePointersAttempted			int   ,
@threePointersMade				int   ,
@threePointersPercentage		float,
@turnovers						int   ,
@twoPointersAttempted			int   ,
@twoPointersMade				int   ,
@twoPointersPercentage			float,
@assistsTurnoverRatio			float,
@benchPoints					int   ,
@biggestLead					int   ,
@biggestLeadScore				varchar(30),
@biggestScoringRun				int   ,
@biggestScoringRunScore			varchar(30),
@fastBreakPointsAttempted		int   ,
@fastBreakPointsMade			int   ,
@fastBreakPointsPercentage		float,
@fieldGoalsEffectiveAdjusted	float,
@foulsTeam						int   ,
@foulsTeamTechnical				int   ,
@leadChanges					int   ,
@pointsFromTurnovers			int   ,
@pointsInThePaintAttempted		int   ,
@pointsInThePaintMade			int   ,
@pointsInThePaintPercentage		float,
@reboundsPersonal				int   ,
@reboundsTeam					int   ,
@reboundsTeamDefensive			int   ,
@reboundsTeamOffensive			int   ,
@secondChancePointsAttempted	int   ,
@secondChancePointsMade			int   ,
@secondChancePointsPercentage	float,
@timeLeading					varchar(30),
@timesTied						int   ,
@trueShootingAttempts			float,
@trueShootingPercentage			float,
@turnoversTeam					int   ,
@turnoversTotal					int   
as
insert into teamBoxPlayoffs values(
@season_id						,
@series_id						,
@game_id						,
@game							,
@team_id						,
@atHome							,
@matchup_id						,
@points							,
@pointsAgainst					,
@q1Points						,
@q1PointsAgainst				,
@q2Points						,
@q2PointsAgainst				,
@q3Points						,
@q3PointsAgainst				,
@q4Points						,
@q4PointsAgainst				,
@otPoints						,
@otPointsAgainst				,
@assists						,
@blocks							,
@blocksReceived					,
@fieldGoalsAttempted			,
@fieldGoalsMade					,
@fieldGoalsPercentage			,
@foulsOffensive					,
@foulsDrawn						,
@foulsPersonal					,
@foulsTechnical					,
@freeThrowsAttempted			,
@freeThrowsMade					,
@freeThrowsPercentage			,
@minus							,
@minutes						,
@minutesCalculated				,
@plus							,
@plusMinusPoints				,
@pointsFastBreak				,
@pointsInThePaint				,
@pointsSecondChance				,
@reboundsDefensive				,
@reboundsOffensive				,
@reboundsTotal					,
@steals							,
@threePointersAttempted			,
@threePointersMade				,
@threePointersPercentage		,
@turnovers						,
@twoPointersAttempted			,
@twoPointersMade				,
@twoPointersPercentage			,
@assistsTurnoverRatio			,
@benchPoints					,
@biggestLead					,
@biggestLeadScore				,
@biggestScoringRun				,
@biggestScoringRunScore			,
@fastBreakPointsAttempted		,
@fastBreakPointsMade			,
@fastBreakPointsPercentage		,
@fieldGoalsEffectiveAdjusted	,
@foulsTeam						,
@foulsTeamTechnical				,
@leadChanges					,
@pointsFromTurnovers			,
@pointsInThePaintAttempted		,
@pointsInThePaintMade			,
@pointsInThePaintPercentage		,
@reboundsPersonal				,
@reboundsTeam					,
@reboundsTeamDefensive			,
@reboundsTeamOffensive			,
@secondChancePointsAttempted	,
@secondChancePointsMade			,
@secondChancePointsPercentage	,
@timeLeading					,
@timesTied						,
@trueShootingAttempts			,
@trueShootingPercentage			,
@turnoversTeam					,
@turnoversTotal					)
