

create procedure ToolboxAverages @player int, @team int, @season int
as
select
pba.season_id Season, 
pba.player_id, 
pba.team_id, 
pba.Name, 
pba.Team, 
pba.Games, 
pba.Minutes, 
pba.Points, 
pba.Assists, 
pba.Rebounds, 
pba.Blocks, 
pba.Steals,
pba.FGM, 
pba.FGA, 
pba.[FG%], 
pba.FG3M, 
pba.FG3A, 
pba.[FG3%], 
pba.FG2M, 
pba.FG2A, 
pba.[FG2%], 
pba.FTM, 
pba.FTA, 
pba.[FT%],
pt.Minutes		TrendMinutes, 	
pt.Points	    TrendPoints, 
pt.Assists	    TrendAssists, 
pt.Rebounds     TrendRebounds, 
pt.Blocks	    TrendBlocks, 
pt.Steals	    TrendSteals, 
pt.FGM		    TrendFGM, 
pt.FGA		    TrendFGA, 
pt.[FG%]	    [TrendFG%], 
pt.FG3M		    TrendFG3M, 
pt.FG3A		    TrendFG3A, 
pt.[FG3%]	    [TrendFG3%], 
pt.FG2M         TrendFG2M, 
pt.FG2A         TrendFG2A, 
pt.[FG2%]       [TrendFG2%], 
pt.FTM          TrendFTM, 
pt.FTA          TrendFTA, 
pt.[FT%]        [TrendFT%],
pt.Minutes	- pba.Minutes  diffMinutes,
pt.Points	- pba.Points   diffPoints  ,
pt.Assists	- pba.Assists  diffAssists ,
pt.Rebounds	- pba.Rebounds diffRebounds,
pt.Blocks	- pba.Blocks   diffBlocks  ,
pt.Steals	- pba.Steals   diffSteals  ,
pt.FGM		- pba.FGM      diffFGM     ,
pt.FGA		- pba.FGA      diffFGA     ,
pt.[FG%]	- pba.[FG%]    [diffFG%]   ,
pt.FG3M		- pba.FG3M     diffFG3M    ,
pt.FG3A		- pba.FG3A     diffFG3A    ,
pt.[FG3%]	- pba.[FG3%]   [diffFG3%]  ,
pt.FG2M    	- pba.FG2M     diffFG2M    ,
pt.FG2A    	- pba.FG2A     diffFG2A    ,
pt.[FG2%]  	- pba.[FG2%]   [diffFG2%]  ,
pt.FTM     	- pba.FTM      diffFTM     ,
pt.FTA     	- pba.FTA      diffFTA     ,
pt.[FT%]   	- pba.[FT%]    [diffFT%]   , 
[PtsDeviation]						   ,
[AstDeviation]						   ,
[RebDeviation]						   ,
[BlkDeviation]						   ,
[StlDeviation]						   ,
[FGMDeviation]						   ,
[FGADeviation]						   ,
[FG3MDeviation]						   ,
[FG3ADeviation]						   ,
[MinDeviation]						   ,
[FG2MDeviation]						   ,
[FG2ADeviation]						   ,
[FTMDeviation]						   ,
[FTADeviation]
from playerBoxAverage pba inner join
		PlayerTrend5 pt on pba.player_id = pt.player_id and pba.team_id = pt.team_id inner join
		PlayerTrend5StdDeviation s on pba.player_id = s.player_id and pba.team_id = s.team_id
where pba.player_id = @player and pba.team_id = @team
and pba.season_id = 2024
