  select * from [arena]			    where season_id = 2024
  select * from [game]				where season_id = 2024		order by game_id desc
  select * from [official]			where season_id = 2024
  select * from [playByPlay]			where season_id = 2024	order by game_id desc
--select * from playByPlayPlayoffs	where season_id = 2024		order by game_id desc
  select * from [player]				where season_id = 2024
  select * from [playerBox]			where season_id = 2024		order by game_id desc
--select * from playerBoxPlayoffs		where season_id = 2024	order by game_id desc
  select * from PlayerTeam			where season_id = 2024
--select * from [PlayoffBracket]		where season_id = 2024	order by game_id desc
--select * from [PlayoffPicture]		where season_id = 2024	order by game_id desc
--select * from PlayoffSeries			where season_id = 2024	order by game_id desc
  select * from team					where season_id = 2024
  select * from teamBox				where season_id = 2024		order by game_id desc
--select * from teamBoxPlayoffs		where season_id = 2024		order by game_id desc