create  procedure ParlayTeamAverageRanks @team int, @season int
as
select t.season_id
      , t.team_id
      , t.Team
      , t.points
      , t.pointsAgainst
      , t.MoV
      , t.q1Points
      , t.q1PointsAgainst
      , t.q2Points
      , t.q2PointsAgainst
      , t.q3Points
      , t.q3PointsAgainst
      , t.q4Points
      , t.q4PointsAgainst
      , t.otPoints
      , t.otPointsAgainst
      , t.assists
      , t.blocks
      , t.blocksReceived
      , t.fieldGoalsAttempted
      , t.fieldGoalsMade
      , t.fieldGoalsPercentage
      , t.foulsOffensive
      , t.foulsDrawn
      , t.foulsPersonal
      , t.foulsTechnical
      , t.freeThrowsAttempted
      , t.freeThrowsMade
      , t.freeThrowsPercentage
      , t.minus
      , t.plus
      , t.plusMinusPoints
      , t.pointsFastBreak
      , t.pointsInThePaint
      , t.pointsSecondChance
      , t.reboundsDefensive
      , t.reboundsOffensive
      , t.reboundsTotal
      , t.steals
      , t.threePointersAttempted
      , t.threePointersMade
      , t.threePointersPercentage
      , t.turnovers
      , t.twoPointersAttempted
      , t.twoPointersMade
      , t.twoPointersPercentage
      , t.assistsTurnoverRatio
      , t.benchPoints
      , t.biggestLead
      , t.biggestScoringRun
      , t.fastBreakPointsAttempted
      , t.fastBreakPointsMade
      , t.fastBreakPointsPercentage
      , t.fieldGoalsEffectiveAdjusted
      , t.foulsTeam
      , t.foulsTeamTechnical
      , t.leadChanges
      , t.pointsFromTurnovers
      , t.pointsInThePaintAttempted
      , t.pointsInThePaintMade
      , t.pointsInThePaintPercentage
      , t.reboundsPersonal
      , t.reboundsTeam
      , t.reboundsTeamDefensive
      , t.reboundsTeamOffensive
      , t.secondChancePointsAttempted
      , t.secondChancePointsMade
      , t.secondChancePointsPercentage
      , t.timesTied
      , t.trueShootingAttempts
      , t.trueShootingPercentage
      , t.turnoversTeam
      , t.turnoversTotal
      , t.pointsRank
      , t.pointsAgainstRank
      , t.MoVRank
      , t.q1PointsRank
      , t.q1PointsAgainstRank
      , t.q2PointsRank
      , t.q2PointsAgainstRank
      , t.q3PointsRank
      , t.q3PointsAgainstRank
      , t.q4PointsRank
      , t.q4PointsAgainstRank
      , t.otPointsRank
      , t.otPointsAgainstRank
      , t.assistsRank
      , t.blocksRank
      , t.blocksReceivedRank
      , t.fieldGoalsAttemptedRank
      , t.fieldGoalsMadeRank
      , t.fieldGoalsPercentageRank
      , t.foulsOffensiveRank
      , t.foulsDrawnRank
      , t.foulsPersonalRank
      , t.foulsTechnicalRank
      , t.freeThrowsAttemptedRank
      , t.freeThrowsMadeRank
      , t.freeThrowsPercentageRank
      , t.minusRank
      , t.plusRank
      , t.plusMinusPointsRank
      , t.pointsFastBreakRank
      , t.pointsInThePaintRank
      , t.pointsSecondChanceRank
      , t.reboundsDefensiveRank
      , t.reboundsOffensiveRank
      , t.reboundsTotalRank
      , t.stealsRank
      , t.threePointersAttemptedRank
      , t.threePointersMadeRank
      , t.threePointersPercentageRank
      , t.turnoversRank
      , t.twoPointersAttemptedRank
      , t.twoPointersMadeRank
      , t.twoPointersPercentageRank
      , t.assistsTurnoverRatioRank
      , t.benchPointsRank
      , t.biggestLeadRank
      , t.biggestScoringRunRank
      , t.fastBreakPointsAttemptedRank
      , t.fastBreakPointsMadeRank
      , t.fastBreakPointsPercentageRank
      , t.fieldGoalsEffectiveAdjustedRank
      , t.foulsTeamRank
      , t.foulsTeamTechnicalRank
      , t.leadChangesRank
      , t.pointsFromTurnoversRank
      , t.pointsInThePaintAttemptedRank
      , t.pointsInThePaintMadeRank
      , t.pointsInThePaintPercentageRank
      , t.reboundsPersonalRank
      , t.reboundsTeamRank
      , t.reboundsTeamDefensiveRank
      , t.reboundsTeamOffensiveRank
      , t.secondChancePointsAttemptedRank
      , t.secondChancePointsMadeRank
      , t.secondChancePointsPercentageRank
      , t.timesTiedRank
      , t.trueShootingAttemptsRank
      , t.trueShootingPercentageRank
      , t.turnoversTeamRank
      , t.turnoversTotalRank
	  , o.matchup_id
      , o.opAssists
      , o.opFieldGoalsAttempted
      , o.opFieldGoalsMade
      , o.opFieldGoalsPercentage
      , o.opFoulsOffensive
      , o.opFoulsDrawn
      , o.opFoulsPersonal
      , o.opFoulsTechnical
      , o.opFreeThrowsAttempted
      , o.opFreeThrowsMade
      , o.opFreeThrowsPercentage
      , o.opMinus
      , o.opPlus
      , o.opPlusMinusPoints
      , o.opPointsFastBreak
      , o.opPointsInThePaint
      , o.opPointsSecondChance
      , o.opReboundsDefensive
      , o.opReboundsOffensive
      , o.opReboundsTotal
      , o.opSteals
      , o.opThreePointersAttempted
      , o.opThreePointersMade
      , o.opThreePointersPercentage
      , o.opTurnovers
      , o.opTwoPointersAttempted
      , o.opTwoPointersMade
      , o.opTwoPointersPercentage
      , o.opAssistsTurnoverRatio
      , o.opBenchPoints
      , o.opBiggestLead
      , o.opBiggestScoringRun
      , o.opFastBreakPointsAttempted
      , o.opFastBreakPointsMade
      , o.opFastBreakPointsPercentage
      , o.opFieldGoalsEffectiveAdjusted
      , o.opFoulsTeam
      , o.opFoulsTeamTechnical
      , o.opLeadChanges
      , o.opPointsFromTurnovers
      , o.opPointsInThePaintAttempted
      , o.opPointsInThePaintMade
      , o.opPointsInThePaintPercentage
      , o.opReboundsPersonal
      , o.opReboundsTeam
      , o.opReboundsTeamDefensive
      , o.opReboundsTeamOffensive
      , o.opSecondChancePointsAttempted
      , o.opSecondChancePointsMade
      , o.opSecondChancePointsPercentage
      , o.opTimesTied
      , o.opTrueShootingAttempts
      , o.opTrueShootingPercentage
      , o.opTurnoversTeam
      , o.opTurnoversTotal
      , o.opassistsRank
      , o.opfieldGoalsAttemptedRank
      , o.opfieldGoalsMadeRank
      , o.opfieldGoalsPercentageRank
      , o.opfoulsOffensiveRank
      , o.opfoulsDrawnRank
      , o.opfoulsPersonalRank
      , o.opfoulsTechnicalRank
      , o.opfreeThrowsAttemptedRank
      , o.opfreeThrowsMadeRank
      , o.opfreeThrowsPercentageRank
      , o.opminusRank
      , o.opplusRank
      , o.opplusMinusPointsRank
      , o.oppointsFastBreakRank
      , o.oppointsInThePaintRank
      , o.oppointsSecondChanceRank
      , o.opreboundsDefensiveRank
      , o.opreboundsOffensiveRank
      , o.opreboundsTotalRank
      , o.opstealsRank
      , o.opthreePointersAttemptedRank
      , o.opthreePointersMadeRank
      , o.opthreePointersPercentageRank
      , o.opturnoversRank
      , o.optwoPointersAttemptedRank
      , o.optwoPointersMadeRank
      , o.optwoPointersPercentageRank
      , o.opassistsTurnoverRatioRank
      , o.opbenchPointsRank
      , o.opbiggestLeadRank
      , o.opbiggestScoringRunRank
      , o.opfastBreakPointsAttemptedRank
      , o.opfastBreakPointsMadeRank
      , o.opfastBreakPointsPercentageRank
      , o.opfieldGoalsEffectiveAdjustedRank
      , o.opfoulsTeamRank
      , o.opfoulsTeamTechnicalRank
      , o.opleadChangesRank
      , o.oppointsFromTurnoversRank
      , o.oppointsInThePaintAttemptedRank
      , o.oppointsInThePaintMadeRank
      , o.oppointsInThePaintPercentageRank
      , o.opreboundsPersonalRank
      , o.opreboundsTeamRank
      , o.opreboundsTeamDefensiveRank
      , o.opreboundsTeamOffensiveRank
      , o.opsecondChancePointsAttemptedRank
      , o.opsecondChancePointsMadeRank
      , o.opsecondChancePointsPercentageRank
      , o.optimesTiedRank
      , o.optrueShootingAttemptsRank
      , o.optrueShootingPercentageRank
      , o.opturnoversTeamRank
      , o.opturnoversTotalRank
	  , e.Conference
      , e.tricode
      , e.city
      , e.name
      , e.FullName
      , e.Wins
      , e.Losses
      , e.ConferenceRank
      , e.LeagueRank
from teamBoxAverageRanks t inner join
		opTeamBoxAverageRanks o on t.team_id = o.matchup_id and t.season_id = o.season_id inner join
		TeamExtended e on t.team_id = e.team_id and t.season_id = e.season_id
where t.team_id = @team and t.season_id = @season