SELECT TOP (1000) [season_id]
      ,[player_id]
      ,[name]
      ,[number]
      ,[position]
      ,[college]
      ,[country]
      ,[draftYear]
      ,[draftRound]
      ,[draftPick]
  FROM [NBAdb].[dbo].[player]
