/****** Script for SelectTopNRows command from SSMS  ******/
create view teamBoxAverageRanks
as
SELECT [season_id]
      ,[team_id]
      ,[Team]
      ,[points]
      ,[pointsAgainst]
      ,[MoV]
      ,[q1Points]
      ,[q1PointsAgainst]
      ,[q2Points]
      ,[q2PointsAgainst]
      ,[q3Points]
      ,[q3PointsAgainst]
      ,[q4Points]
      ,[q4PointsAgainst]
      ,[otPoints]
      ,[otPointsAgainst]
      ,[assists]
      ,[blocks]
      ,[blocksReceived]
      ,[fieldGoalsAttempted]
      ,[fieldGoalsMade]
      ,[fieldGoalsPercentage]
      ,[foulsOffensive]
      ,[foulsDrawn]
      ,[foulsPersonal]
      ,[foulsTechnical]
      ,[freeThrowsAttempted]
      ,[freeThrowsMade]
      ,[freeThrowsPercentage]
      ,[minus]
      ,[plus]
      ,[plusMinusPoints]
      ,[pointsFastBreak]
      ,[pointsInThePaint]
      ,[pointsSecondChance]
      ,[reboundsDefensive]
      ,[reboundsOffensive]
      ,[reboundsTotal]
      ,[steals]
      ,[threePointersAttempted]
      ,[threePointersMade]
      ,[threePointersPercentage]
      ,[turnovers]
      ,[twoPointersAttempted]
      ,[twoPointersMade]
      ,[twoPointersPercentage]
      ,[assistsTurnoverRatio]
      ,[benchPoints]
      ,[biggestLead]
      ,[biggestScoringRun]
      ,[fastBreakPointsAttempted]
      ,[fastBreakPointsMade]
      ,[fastBreakPointsPercentage]
      ,[fieldGoalsEffectiveAdjusted]
      ,[foulsTeam]
      ,[foulsTeamTechnical]
      ,[leadChanges]
      ,[pointsFromTurnovers]
      ,[pointsInThePaintAttempted]
      ,[pointsInThePaintMade]
      ,[pointsInThePaintPercentage]
      ,[reboundsPersonal]
      ,[reboundsTeam]
      ,[reboundsTeamDefensive]
      ,[reboundsTeamOffensive]
      ,[secondChancePointsAttempted]
      ,[secondChancePointsMade]
      ,[secondChancePointsPercentage]
      ,[timesTied]
      ,[trueShootingAttempts]
      ,[trueShootingPercentage]
      ,[turnoversTeam]
      ,[turnoversTotal]
      ,rank()OVER (PARTITION by season_id order by [points]							desc)[pointsRank]							
      ,rank()OVER (PARTITION by season_id order by [pointsAgainst]					asc)[pointsAgainstRank]					
      ,rank()OVER (PARTITION by season_id order by [MoV]							desc)[MoVRank]							
      ,rank()OVER (PARTITION by season_id order by [q1Points]						desc)[q1PointsRank]						
      ,rank()OVER (PARTITION by season_id order by [q1PointsAgainst]				asc)[q1PointsAgainstRank]				
      ,rank()OVER (PARTITION by season_id order by [q2Points]						desc)[q2PointsRank]						
      ,rank()OVER (PARTITION by season_id order by [q2PointsAgainst]				asc)[q2PointsAgainstRank]				
      ,rank()OVER (PARTITION by season_id order by [q3Points]						desc)[q3PointsRank]						
      ,rank()OVER (PARTITION by season_id order by [q3PointsAgainst]				asc)[q3PointsAgainstRank]				
      ,rank()OVER (PARTITION by season_id order by [q4Points]						desc)[q4PointsRank]						
      ,rank()OVER (PARTITION by season_id order by [q4PointsAgainst]				asc)[q4PointsAgainstRank]				
      ,rank()OVER (PARTITION by season_id order by [otPoints]						desc)[otPointsRank]						
      ,rank()OVER (PARTITION by season_id order by [otPointsAgainst]				asc)[otPointsAgainstRank]				
      ,rank()OVER (PARTITION by season_id order by [assists]						desc)[assistsRank]						
      ,rank()OVER (PARTITION by season_id order by [blocks]							desc)[blocksRank]							
      ,rank()OVER (PARTITION by season_id order by [blocksReceived]					desc)[blocksReceivedRank]					
      ,rank()OVER (PARTITION by season_id order by [fieldGoalsAttempted]			desc)[fieldGoalsAttemptedRank]			
      ,rank()OVER (PARTITION by season_id order by [fieldGoalsMade]					desc)[fieldGoalsMadeRank]					
      ,rank()OVER (PARTITION by season_id order by [fieldGoalsPercentage]			desc)[fieldGoalsPercentageRank]			
      ,rank()OVER (PARTITION by season_id order by [foulsOffensive]					desc)[foulsOffensiveRank]					
      ,rank()OVER (PARTITION by season_id order by [foulsDrawn]						desc)[foulsDrawnRank]						
      ,rank()OVER (PARTITION by season_id order by [foulsPersonal]					desc)[foulsPersonalRank]					
      ,rank()OVER (PARTITION by season_id order by [foulsTechnical]					desc)[foulsTechnicalRank]					
      ,rank()OVER (PARTITION by season_id order by [freeThrowsAttempted]			desc)[freeThrowsAttemptedRank]			
      ,rank()OVER (PARTITION by season_id order by [freeThrowsMade]					desc)[freeThrowsMadeRank]					
      ,rank()OVER (PARTITION by season_id order by [freeThrowsPercentage]			desc)[freeThrowsPercentageRank]			
      ,rank()OVER (PARTITION by season_id order by [minus]							desc)[minusRank]							
      ,rank()OVER (PARTITION by season_id order by [plus]							desc)[plusRank]							
      ,rank()OVER (PARTITION by season_id order by [plusMinusPoints]				desc)[plusMinusPointsRank]				
      ,rank()OVER (PARTITION by season_id order by [pointsFastBreak]				desc)[pointsFastBreakRank]				
      ,rank()OVER (PARTITION by season_id order by [pointsInThePaint]				desc)[pointsInThePaintRank]				
      ,rank()OVER (PARTITION by season_id order by [pointsSecondChance]				desc)[pointsSecondChanceRank]				
      ,rank()OVER (PARTITION by season_id order by [reboundsDefensive]				desc)[reboundsDefensiveRank]				
      ,rank()OVER (PARTITION by season_id order by [reboundsOffensive]				desc)[reboundsOffensiveRank]				
      ,rank()OVER (PARTITION by season_id order by [reboundsTotal]					desc)[reboundsTotalRank]					
      ,rank()OVER (PARTITION by season_id order by [steals]							desc)[stealsRank]							
      ,rank()OVER (PARTITION by season_id order by [threePointersAttempted]			desc)[threePointersAttemptedRank]			
      ,rank()OVER (PARTITION by season_id order by [threePointersMade]				desc)[threePointersMadeRank]				
      ,rank()OVER (PARTITION by season_id order by [threePointersPercentage]		desc)[threePointersPercentageRank]		
      ,rank()OVER (PARTITION by season_id order by [turnovers]						desc)[turnoversRank]						
      ,rank()OVER (PARTITION by season_id order by [twoPointersAttempted]			desc)[twoPointersAttemptedRank]			
      ,rank()OVER (PARTITION by season_id order by [twoPointersMade]				desc)[twoPointersMadeRank]				
      ,rank()OVER (PARTITION by season_id order by [twoPointersPercentage]			desc)[twoPointersPercentageRank]			
      ,rank()OVER (PARTITION by season_id order by [assistsTurnoverRatio]			desc)[assistsTurnoverRatioRank]			
      ,rank()OVER (PARTITION by season_id order by [benchPoints]					desc)[benchPointsRank]					
      ,rank()OVER (PARTITION by season_id order by [biggestLead]					desc)[biggestLeadRank]					
      ,rank()OVER (PARTITION by season_id order by [biggestScoringRun]				desc)[biggestScoringRunRank]				
      ,rank()OVER (PARTITION by season_id order by [fastBreakPointsAttempted]		desc)[fastBreakPointsAttemptedRank]		
      ,rank()OVER (PARTITION by season_id order by [fastBreakPointsMade]			desc)[fastBreakPointsMadeRank]			
      ,rank()OVER (PARTITION by season_id order by [fastBreakPointsPercentage]		desc)[fastBreakPointsPercentageRank]		
      ,rank()OVER (PARTITION by season_id order by [fieldGoalsEffectiveAdjusted]	desc)[fieldGoalsEffectiveAdjustedRank]	
      ,rank()OVER (PARTITION by season_id order by [foulsTeam]						desc)[foulsTeamRank]						
      ,rank()OVER (PARTITION by season_id order by [foulsTeamTechnical]				desc)[foulsTeamTechnicalRank]				
      ,rank()OVER (PARTITION by season_id order by [leadChanges]					desc)[leadChangesRank]					
      ,rank()OVER (PARTITION by season_id order by [pointsFromTurnovers]			desc)[pointsFromTurnoversRank]			
      ,rank()OVER (PARTITION by season_id order by [pointsInThePaintAttempted]		desc)[pointsInThePaintAttemptedRank]		
      ,rank()OVER (PARTITION by season_id order by [pointsInThePaintMade]			desc)[pointsInThePaintMadeRank]			
      ,rank()OVER (PARTITION by season_id order by [pointsInThePaintPercentage]		desc)[pointsInThePaintPercentageRank]	
      ,rank()OVER (PARTITION by season_id order by [reboundsPersonal]				desc)[reboundsPersonalRank]				
      ,rank()OVER (PARTITION by season_id order by [reboundsTeam]					desc)[reboundsTeamRank]					
      ,rank()OVER (PARTITION by season_id order by [reboundsTeamDefensive]			desc)[reboundsTeamDefensiveRank]			
      ,rank()OVER (PARTITION by season_id order by [reboundsTeamOffensive]			desc)[reboundsTeamOffensiveRank]			
      ,rank()OVER (PARTITION by season_id order by [secondChancePointsAttempted]	desc)[secondChancePointsAttemptedRank]	
      ,rank()OVER (PARTITION by season_id order by [secondChancePointsMade]			desc)[secondChancePointsMadeRank]			
      ,rank()OVER (PARTITION by season_id order by [secondChancePointsPercentage]	desc)[secondChancePointsPercentageRank]	
      ,rank()OVER (PARTITION by season_id order by [timesTied]						desc)[timesTiedRank]						
      ,rank()OVER (PARTITION by season_id order by [trueShootingAttempts]			desc)[trueShootingAttemptsRank]			
      ,rank()OVER (PARTITION by season_id order by [trueShootingPercentage]			desc)[trueShootingPercentageRank]			
      ,rank()OVER (PARTITION by season_id order by [turnoversTeam]					desc)[turnoversTeamRank]					
      ,rank()OVER (PARTITION by season_id order by [turnoversTotal]					desc)[turnoversTotalRank]					
  FROM [NBAdb].[dbo].[teamBoxAverage]



